server:
  port: 9020


spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vivek363singh/config-server
          default-label: main
          clone-on-start: true